export const GOOD_BUGS = [
  {
    name: "Native bees",
    examples: "Bumble bees, mason bees, mining bees, sweat bees and others",
    role: "Pollination",
    value: "Different bee species work at different temperatures, flower shapes and times of year. Bumble bees can buzz-pollinate crops such as tomatoes.",
    support: ["Provide flowers from spring through fall", "Leave some bare/undisturbed soil and appropriate stem habitat", "Avoid spraying blooms", "Provide shallow clean water"],
    caution: "Not every bee lives in a hive. Ground-nesting native bees can be mistaken for pests.",
    sourceKeys: ["PSU_POLLINATORS"]
  },
  {
    name: "Honey bees",
    examples: "Apis mellifera",
    role: "Pollination",
    value: "Managed colonies can move large numbers of foragers through mass-flowering crops and are important agricultural pollinators.",
    support: ["Provide diverse blooms", "Avoid exposing bees to pesticide applications", "Keep water available"],
    caution: "Honey bees are managed, non-native livestock in North America; protecting native pollinator diversity matters too.",
    sourceKeys: ["PSU_POLLINATORS"]
  },
  {
    name: "Bumble bees",
    examples: "Bombus species",
    role: "Pollination",
    value: "Strong pollinators in cool conditions and excellent buzz pollinators of tomato-family flowers.",
    support: ["Keep flowering resources continuous", "Preserve safe nesting/overwintering habitat", "Reduce broad-spectrum insecticides"],
    caution: "Greenhouse tomatoes may be pollinated by managed bumble bees commercially, but small growers can also use plant vibration or hand methods.",
    sourceKeys: ["PSU_POLLINATORS"]
  },
  {
    name: "Hover flies",
    examples: "Syrphid flies",
    role: "Pollination + predation",
    value: "Adults visit flowers; larvae of many species consume aphids and other soft-bodied pests.",
    support: ["Plant small open flowers", "Avoid killing unfamiliar fly larvae", "Maintain flowering habitat"],
    caution: "Adults often mimic bees/wasps but generally do not sting.",
    sourceKeys: ["PSU_BENEFICIALS"]
  },
  {
    name: "Lady beetles",
    examples: "Ladybugs; adults and larvae",
    role: "Predation",
    value: "Many species consume aphids, scales and other soft-bodied insects.",
    support: ["Learn the alligator-like larval form", "Avoid broad-spectrum sprays when predators are present", "Provide flowering resources"],
    caution: "Do not assume every spotted beetle is beneficial; Mexican bean beetles are plant-feeding relatives.",
    sourceKeys: ["UT_INSECTS", "PSU_BENEFICIALS"]
  },
  {
    name: "Green lacewings",
    examples: "Chrysopidae",
    role: "Predation",
    value: "Larvae attack aphids, small caterpillars, insect eggs, whiteflies and other small prey.",
    support: ["Provide nectar/pollen plants for adults", "Avoid unnecessary sprays", "Recognize eggs held on tiny stalks"],
    caution: "The delicate adult and the predatory larva look completely different.",
    sourceKeys: ["UT_INSECTS", "PSU_BENEFICIALS"]
  },
  {
    name: "Parasitoid wasps",
    examples: "Many tiny non-stinging-to-humans species",
    role: "Parasitoid",
    value: "Lay eggs in or on pest insects; developing offspring kill the host. Important against aphids, caterpillars and many other pests.",
    support: ["Grow tiny-flowered nectar plants", "Leave parasitized 'mummified' aphids in place when practical", "Avoid broad-spectrum insecticides"],
    caution: "Most useful parasitoids are tiny and easily overlooked; killing all wasps removes important natural control.",
    sourceKeys: ["UT_INSECTS", "PSU_BENEFICIALS"]
  },
  {
    name: "Minute pirate bugs",
    examples: "Orius species",
    role: "Predation",
    value: "Attack thrips, mites, aphids and insect eggs.",
    support: ["Maintain plant diversity", "Reduce disruptive insecticides", "Provide pollen/flower resources"],
    caution: "They can occasionally give people a harmless but noticeable exploratory bite.",
    sourceKeys: ["PSU_BENEFICIALS"]
  },
  {
    name: "Assassin and damsel bugs",
    examples: "Reduviidae and Nabidae",
    role: "Predation",
    value: "Generalist hunters that attack many crop pests.",
    support: ["Maintain habitat", "Avoid indiscriminate spraying", "Learn to distinguish them from plant-feeding true bugs"],
    caution: "Assassin bugs can bite if handled; observe rather than picking them up.",
    sourceKeys: ["UT_INSECTS", "PSU_BENEFICIALS"]
  },
  {
    name: "Ground beetles",
    examples: "Carabidae",
    role: "Predation",
    value: "Many hunt at soil level and feed on insect eggs, larvae, slugs and other small organisms.",
    support: ["Maintain mulch/refuge zones without waterlogging", "Avoid unnecessary soil insecticides", "Provide permanent habitat near beds"],
    caution: "Many are nocturnal; seeing a fast dark beetle on the soil does not automatically mean crop damage.",
    sourceKeys: ["UT_INSECTS"]
  },
  {
    name: "Spiders",
    examples: "Orb weavers, jumping spiders, wolf spiders and others",
    role: "Predation",
    value: "Not insects, but major garden predators that consume flies, moths, leafhoppers and many other insects.",
    support: ["Avoid destroying every web", "Use targeted rather than broad-spectrum controls", "Maintain structural habitat"],
    caution: "Spiders are generalists and may take beneficial insects too, but are an important part of the garden food web.",
    sourceKeys: ["UT_INSECTS", "PSU_BENEFICIALS"]
  },
  {
    name: "Praying mantids",
    examples: "Mantises",
    role: "Generalist predation",
    value: "Eat many insects and are fascinating garden predators.",
    support: ["Allow locally occurring mantids to remain", "Preserve general habitat"],
    caution: "They are not precision pest-control agents and also eat bees, butterflies and other beneficials. Avoid buying imported/non-native egg cases as a 'biocontrol' shortcut.",
    sourceKeys: ["UT_INSECTS"]
  }
];

export const BAD_BUGS = [
  {
    name: "Aphids",
    type: "Sap feeder",
    crops: "Greens, brassicas, peas, beans, peppers, tomatoes and many ornamentals",
    id: "Clusters of small soft-bodied insects on new growth or leaf undersides; cast skins; sticky honeydew; curled leaves.",
    damage: "Sap removal, distorted growth, honeydew/sooty mold and virus transmission by some species.",
    now: ["Confirm aphids are alive and increasing; old skins can make a colony look larger", "Blast small colonies with water where crop structure permits", "Pinch/prune heavily infested tips", "Protect lady beetles, lacewings, hoverfly larvae and parasitoid wasps"],
    prevent: ["Avoid excessive nitrogen that produces lush susceptible growth", "Control relevant weeds/reservoirs", "Inspect transplants before greenhouse/tent entry"],
    treatment: "If pressure remains damaging, use a crop- and pest-labeled least-disruptive product and thoroughly target the insects; repeat only as the label allows.",
    netNote: "Fine mesh may exclude winged colonizers but can also exclude predators; aphids already inside can reproduce rapidly.",
    sourceKeys: ["UT_INSECTS", "PSU_BENEFICIALS"]
  },
  {
    name: "Flea beetles",
    type: "Chewing beetle",
    crops: "Eggplant, brassicas, radish, turnip and other hosts",
    id: "Tiny jumping beetles; leaves develop many small round 'shot holes.'",
    damage: "Seedlings can be stunted or killed; established plants often tolerate moderate feeding.",
    now: ["Protect young plants early", "Use row cover/insect mesh before beetles arrive", "Remove badly damaged seedlings if recovery is poor"],
    prevent: ["Reduce nearby host weeds", "Use vigorous transplants", "Rotate where practical"],
    treatment: "Use labeled controls only when feeding threatens establishment; mature plants may not need treatment.",
    netNote: "Excellent row-cover candidate because the key damage is often before flowering; ensure pests did not emerge from soil already under the cover.",
    sourceKeys: ["UT_INSECTS", "NCSU_IPM"]
  },
  {
    name: "Cutworms",
    type: "Caterpillar",
    crops: "Young transplants and seedlings",
    id: "Seedlings cut at or near soil line; curled gray/brown caterpillar found just under soil or debris nearby.",
    damage: "Can sever entire young plants overnight.",
    now: ["Search soil around damaged plants at dawn", "Hand-remove larvae", "Use a stem collar around vulnerable transplants"],
    prevent: ["Remove heavy weedy growth well before planting", "Cultivate/prepare beds ahead of transplanting where appropriate", "Scout newly planted areas nightly"],
    treatment: "Localized physical protection is often more effective than blanket treatment in a home garden.",
    netNote: "A top net may not stop larvae already in the bed because cutworms hide at soil level.",
    sourceKeys: ["UT_INSECTS"]
  },
  {
    name: "Thrips",
    type: "Sap/rasping feeder",
    crops: "Onion, pepper, flowers, greenhouse crops and many others",
    id: "Very narrow tiny insects; silvery scars, flecking or distorted young tissue; often hidden in flowers/folds.",
    damage: "Feeding injury and transmission of some important plant viruses.",
    now: ["Tap flowers/leaves over white paper to inspect", "Remove heavily infested plant material", "Use sticky cards as monitoring aids in protected culture"],
    prevent: ["Inspect incoming plants", "Manage host weeds", "Use screens appropriate to protected structures without blocking required airflow"],
    treatment: "Diagnosis matters because virus symptoms will not be cured by killing the vector after infection.",
    netNote: "Very fine mesh is required for thrips and can reduce airflow/raise temperature; monitor protected crops carefully.",
    sourceKeys: ["UT_INSECTS", "NCSU_PATH"]
  },
  {
    name: "Squash bugs",
    type: "True bug / sap feeder",
    crops: "Squash and pumpkins; sometimes other cucurbits",
    id: "Bronze-brown egg clusters under leaves; gray nymphs; flattened brown-gray adults.",
    damage: "Leaves wilt and collapse from feeding; heavy populations can severely weaken vines.",
    now: ["Crush/remove egg masses", "Hand-pick adults/nymphs into soapy water", "Remove badly colonized leaves only if enough canopy remains"],
    prevent: ["Clean crop debris after harvest", "Rotate cucurbits where practical", "Scout leaf undersides early and often"],
    treatment: "Young nymphs are generally easier to control than adults; use only labeled products if thresholds justify it.",
    netNote: "Row cover can delay colonization, but open/remove it when bee-pollinated flowers need access unless hand-pollinating.",
    sourceKeys: ["UT_INSECTS", "NCSU_IPM"]
  },
  {
    name: "Squash vine borer",
    type: "Moth larva / stem borer",
    crops: "Summer squash, zucchini and some pumpkins",
    id: "Sudden vine wilt; sawdust-like frass at stem base; larva tunneling inside stem.",
    damage: "Larvae destroy water-conducting stem tissue and can collapse a whole vine.",
    now: ["Inspect stem bases for frass", "Carefully slit a stem to remove larvae on a small planting, then mound moist soil over the wound", "Remove dead vines to prevent continued development"],
    prevent: ["Use row cover before adult moth activity", "Time plantings/choose less susceptible types where practical", "Destroy infested crop residue"],
    treatment: "Once larvae are deep inside stems, sprays have limited reach; prevention and early detection are more effective.",
    netNote: "Cucurbits need pollination. Open/remove covers at flowering or hand-pollinate and reseal carefully.",
    sourceKeys: ["UT_INSECTS", "NCSU_IPM"]
  },
  {
    name: "Striped and spotted cucumber beetles",
    type: "Chewing beetle / disease vector",
    crops: "Cucumber, squash, melon and other cucurbits",
    id: "Small yellow-green beetles with black stripes or spots; chew cotyledons, leaves and flowers.",
    damage: "Seedling feeding plus transmission of bacterial wilt by some cucumber beetles.",
    now: ["Protect seedlings", "Hand-remove in small gardens", "Remove plants strongly suspected of bacterial wilt rather than allowing beetles to move between them"],
    prevent: ["Use row cover early", "Keep cucurbit transplants vigorous", "Manage crop residues and volunteer hosts"],
    treatment: "Vector management must occur early; a wilted infected vine cannot be cured by killing beetles later.",
    netNote: "Remove/open cover for bee-pollinated flowers or hand-pollinate.",
    sourceKeys: ["UT_INSECTS", "NCSU_IPM", "NCSU_PATH"]
  },
  {
    name: "Tomato and tobacco hornworms",
    type: "Large caterpillar",
    crops: "Tomato, pepper, eggplant and related plants",
    id: "Large green caterpillars with diagonal markings and a tail horn; large missing leaf sections and dark droppings.",
    damage: "Rapid defoliation and fruit feeding when larvae are large.",
    now: ["Hand-pick", "Look beneath damaged stems for droppings", "Leave hornworms covered with white parasitoid cocoons in place when practical so beneficial wasps can emerge"],
    prevent: ["Scout from midsummer onward", "Encourage parasitoid habitat"],
    treatment: "Bt products can work best on young caterpillars when labeled for the crop/pest; large larvae are easily hand-removed.",
    netNote: "Tomatoes do not require bee entry in the same way cucurbits do, but fully enclosed plants still need adequate flower vibration/air movement and ventilation.",
    sourceKeys: ["UT_INSECTS", "PSU_BENEFICIALS"]
  },
  {
    name: "Imported cabbageworm",
    type: "Caterpillar",
    crops: "Cabbage, kale, broccoli, cauliflower, collards and other brassicas",
    id: "Velvety green caterpillars; white butterflies commonly seen around brassicas.",
    damage: "Chewed leaves and contamination of heads.",
    now: ["Hand-pick larvae/eggs", "Inspect leaf undersides and developing heads", "Use Bt on small larvae where labeled if needed"],
    prevent: ["Use insect mesh/row cover from planting", "Remove spent brassica residues"],
    treatment: "Target larvae while small and preserve parasitoids.",
    netNote: "Brassicas grown for leaves/heads do not need insect pollination before harvest, so covers can often stay on much longer than on cucurbits.",
    sourceKeys: ["UT_INSECTS", "NCSU_IPM"]
  },
  {
    name: "Cabbage looper",
    type: "Caterpillar",
    crops: "Brassicas and several vegetables",
    id: "Green caterpillar that moves in a looping/inchworm motion.",
    damage: "Ragged leaf holes and head contamination.",
    now: ["Hand-pick", "Inspect inner leaves", "Use labeled Bt while larvae are young if needed"],
    prevent: ["Use insect mesh", "Remove crop residue"],
    treatment: "Biological/targeted caterpillar controls are preferable to broad-spectrum sprays when possible.",
    netNote: "A strong candidate for row cover on leafy/head brassicas.",
    sourceKeys: ["UT_INSECTS"]
  },
  {
    name: "Diamondback moth caterpillar",
    type: "Caterpillar",
    crops: "Brassicas",
    id: "Small green caterpillar that wriggles rapidly and may drop on a silk thread when disturbed.",
    damage: "Windowpane feeding and small holes; can build resistance to insecticides.",
    now: ["Scout carefully", "Hand-remove on small plantings", "Rotate modes of action if a labeled pesticide is truly needed"],
    prevent: ["Use exclusion mesh", "Destroy crop residues/volunteers"],
    treatment: "Avoid repeated use of one pesticide approach; resistance is an important management issue.",
    netNote: "Keep covers sealed at edges; adults are small moths.",
    sourceKeys: ["UT_INSECTS"]
  },
  {
    name: "Whiteflies",
    type: "Sap feeder",
    crops: "Tomatoes, peppers, cucurbits, ornamentals; especially protected culture",
    id: "Tiny white winged adults fly up when foliage is disturbed; scale-like immature stages on leaf undersides; honeydew.",
    damage: "Sap loss, honeydew/sooty mold and virus transmission by some species.",
    now: ["Inspect leaf undersides", "Remove heavily infested leaves without over-defoliating", "Use sticky cards to monitor adults in greenhouse/tent"],
    prevent: ["Quarantine incoming plants", "Screen openings where practical", "Remove crop residue and weed hosts"],
    treatment: "Use an integrated program because eggs/nymphs/adults respond differently; preserve parasitoids/predators where present.",
    netNote: "Fine screening can reduce entry but may decrease ventilation and increase greenhouse heat/humidity.",
    sourceKeys: ["UT_INSECTS", "NCSU_PATH"]
  },
  {
    name: "Spider mites",
    type: "Mite (not an insect)",
    crops: "Beans, tomatoes, cucumbers, strawberries, greenhouse plants and many others",
    id: "Fine stippling/bronzing; tiny mites on leaf undersides; fine webbing under heavy infestation.",
    damage: "Leaf drying and loss of photosynthetic area; populations explode in hot, dry conditions.",
    now: ["Confirm with a hand lens or white-paper tap test", "Rinse leaf undersides where practical", "Remove badly infested material", "Improve plant water stress without waterlogging roots"],
    prevent: ["Avoid dusty stressed conditions", "Inspect protected-culture plants", "Protect predatory mites and other natural enemies"],
    treatment: "Many general insecticides do not control mites and can worsen outbreaks by killing predators.",
    netNote: "Netting is usually not the main answer; mites may arrive on plants and thrive inside hot protected conditions.",
    sourceKeys: ["UT_INSECTS", "PSU_BENEFICIALS"]
  },
  {
    name: "Stink bugs",
    type: "True bug / fruit feeder",
    crops: "Tomato, pepper, beans, corn and fruits",
    id: "Shield-shaped adults; barrel-like egg clusters; nymphs often brightly patterned.",
    damage: "Piercing fruit creates cloudy spots, corky areas, misshapen seeds/fruit and quality loss.",
    now: ["Hand-pick adults/egg masses in small plots", "Scout fruiting plants and field edges", "Identify predatory stink bugs before killing every shield-shaped bug"],
    prevent: ["Manage weeds and crop residues thoughtfully", "Encourage natural enemies"],
    treatment: "Treat only when damage/populations justify it and identity is confirmed.",
    netNote: "Covers become impractical on large fruiting crops and may interfere with pollination/airflow.",
    sourceKeys: ["UT_INSECTS"]
  },
  {
    name: "Harlequin bugs",
    type: "True bug / sap feeder",
    crops: "Brassicas",
    id: "Black shield-shaped bugs with bright orange/red markings; black-and-white barrel-shaped eggs in neat rows.",
    damage: "White/yellow stippling, wilting and plant decline under high populations.",
    now: ["Hand-pick eggs/nymphs/adults", "Remove heavily infested spent plants", "Scout fall brassicas carefully"],
    prevent: ["Remove brassica crop residue and host weeds", "Use row cover on new plantings"],
    treatment: "Physical control is effective in small gardens when started early.",
    netNote: "Well-sealed insect mesh works well on brassicas that are not being grown for seed.",
    sourceKeys: ["UT_INSECTS"]
  },
  {
    name: "Mexican bean beetles",
    type: "Leaf-feeding lady beetle relative",
    crops: "Beans",
    id: "Copper/yellow spotted adults; yellow spiny larvae; leaves skeletonized from undersides.",
    damage: "Severe defoliation can reduce bean yield.",
    now: ["Crush egg clusters", "Hand-pick adults/larvae", "Remove badly damaged leaves only if enough healthy canopy remains"],
    prevent: ["Plant and harvest on schedule", "Destroy crop residue after harvest", "Encourage parasitoids"],
    treatment: "Do not confuse this plant-feeding beetle with predatory lady beetles.",
    netNote: "Row cover can protect young beans but must be managed for crop growth and heat.",
    sourceKeys: ["UT_INSECTS"]
  },
  {
    name: "Colorado potato beetles",
    type: "Leaf-feeding beetle",
    crops: "Potato, eggplant and related crops",
    id: "Yellow-and-black striped adults; orange-red humpbacked larvae; yellow-orange egg clusters.",
    damage: "Rapid defoliation.",
    now: ["Hand-pick adults/larvae", "Crush egg masses", "Act while larvae are small"],
    prevent: ["Rotate solanaceous crops farther away when possible", "Remove volunteers"],
    treatment: "Resistance to insecticides is common; avoid unnecessary/repeated reliance on one chemistry.",
    netNote: "Exclusion can help early, but adults may emerge from overwintering sites and find openings.",
    sourceKeys: ["UT_INSECTS"]
  },
  {
    name: "Corn earworm / tomato fruitworm",
    type: "Caterpillar",
    crops: "Sweet corn, tomato and other crops",
    id: "Variable green/brown caterpillars; feeding in corn ear tips or holes in tomato fruit.",
    damage: "Direct fruit/ear feeding and secondary rot entry.",
    now: ["Remove infested fruit", "Scout silks/fruit", "Hand-pick where practical"],
    prevent: ["Plant timing and cultivar choice can affect pressure", "Clean crop residues"],
    treatment: "Controls must target vulnerable larval stages before larvae are protected deep in ears/fruit.",
    netNote: "Physical exclusion is difficult on corn; bagging individual ears is labor-intensive and timing sensitive.",
    sourceKeys: ["UT_INSECTS"]
  },
  {
    name: "Leafminers",
    type: "Fly or moth larvae",
    crops: "Greens, beets, tomato and many ornamentals",
    id: "Winding or blotchy pale tunnels inside leaves.",
    damage: "Loss of leaf area; cosmetic injury may be tolerable on non-leaf crops.",
    now: ["Remove mined leaves on small plantings", "Crush visible larvae within mines", "Protect parasitoid wasps"],
    prevent: ["Use row cover for susceptible leafy crops", "Manage relevant weeds"],
    treatment: "Contact sprays often cannot reach larvae protected inside leaves.",
    netNote: "Exclusion is more useful than trying to reach an established larva inside the leaf.",
    sourceKeys: ["UT_INSECTS", "PSU_BENEFICIALS"]
  },
  {
    name: "Blister beetles",
    type: "Leaf-feeding beetle",
    crops: "Tomato, potato and other vegetables",
    id: "Elongated soft-bodied beetles, often appearing suddenly in groups.",
    damage: "Rapid leaf stripping when swarms arrive.",
    now: ["Wear gloves and knock beetles into a container rather than crushing on skin", "Protect small high-value plantings"],
    prevent: ["Scout field edges", "Maintain weed management"],
    treatment: "Large sudden aggregations may require a labeled control.",
    netNote: "Mesh may help small beds but beetles can arrive after covers are removed.",
    sourceKeys: ["UT_INSECTS"]
  },
  {
    name: "Slugs and snails",
    type: "Mollusk (not an insect)",
    crops: "Seedlings, greens, strawberries and many tender plants",
    id: "Irregular holes, slime trails, night feeding; hiding under boards/mulch.",
    damage: "Seedling loss and fruit/leaf feeding.",
    now: ["Scout after dark", "Hand-remove", "Reduce unnecessary wet hiding places close to vulnerable seedlings", "Use boards as monitoring/trapping stations"],
    prevent: ["Water early rather than keeping surfaces wet overnight", "Avoid over-mulching directly against seedlings"],
    treatment: "Use only labeled baits compatible with the site and protect children/pets/wildlife according to the label.",
    netNote: "Top netting does not stop slugs already in soil/mulch.",
    sourceKeys: ["UT_INSECTS"]
  },
  {
    name: "Cabbage, onion and seed-corn maggots",
    type: "Fly larvae / root feeder",
    crops: "Brassicas, onions, beans/corn seedlings and other hosts depending on species",
    id: "Poor emergence, wilted seedlings, tunneled roots/stems; small pale legless maggots.",
    damage: "Root and seed injury, especially in cool wet organic soils.",
    now: ["Pull a failing plant and inspect roots", "Remove badly infested plants", "Replant when conditions favor rapid germination if appropriate"],
    prevent: ["Use row cover before adult flies lay eggs", "Avoid planting into large amounts of fresh undecomposed organic matter immediately before susceptible crops", "Use clean vigorous transplants"],
    treatment: "Once larvae are inside roots, rescue options are limited; prevention is key.",
    netNote: "Covers work only if flies cannot emerge from infested soil already enclosed.",
    sourceKeys: ["UT_INSECTS"]
  },
  {
    name: "Wireworms",
    type: "Soil-dwelling beetle larva",
    crops: "Potato, corn, carrots, seedlings and many root crops",
    id: "Slender hard-bodied yellow-brown larvae in soil; tunnels in roots/tubers or damaged germinating seed.",
    damage: "Stand loss and tunneling in underground plant parts.",
    now: ["Dig around damaged plants to confirm larvae", "Remove badly damaged roots/tubers", "Record problem areas for future rotation"],
    prevent: ["Avoid placing highly susceptible crops immediately after long-term sod when possible", "Prepare weedy/sod sites well ahead of planting", "Rotate and scout problem beds"],
    treatment: "Established soil populations are difficult to fix mid-crop; site preparation and rotation are more useful than rescue treatments.",
    netNote: "Row cover does not control larvae already living in soil.",
    sourceKeys: ["UT_INSECTS"]
  },
  {
    name: "White grubs",
    type: "Soil-dwelling beetle larva",
    crops: "Roots of many crops; most damaging in newly converted sod or grassy areas",
    id: "C-shaped creamy larvae with brown heads found in soil.",
    damage: "Root feeding can stunt or kill young plants.",
    now: ["Dig around wilting plants to confirm", "Hand-remove larvae in small beds", "Replace badly damaged transplants after addressing the infestation"],
    prevent: ["Inspect soil when converting turf to garden", "Prepare new beds before planting vulnerable crops", "Keep records of hot spots"],
    treatment: "Treatment depends on grub species and timing; do not treat merely because one grub is present.",
    netNote: "Aerial exclusion does not affect soil-stage grubs.",
    sourceKeys: ["UT_INSECTS"]
  },
  {
    name: "Leafhoppers",
    type: "Sap feeder / possible disease vector",
    crops: "Beans, potatoes and many garden plants",
    id: "Small wedge-shaped insects that jump or fly quickly; pale stippling or edge burn may appear on leaves.",
    damage: "Sap feeding can cause hopperburn, and some species transmit plant pathogens.",
    now: ["Confirm insects on leaf undersides", "Remove heavily infested weeds near crops where appropriate", "Monitor young susceptible plants"],
    prevent: ["Use clean transplants", "Manage weed reservoirs", "Use exclusion mesh on small vulnerable plantings if heat/pollination allow"],
    treatment: "Whether treatment is justified depends on crop, species and disease-vector risk.",
    netNote: "Mesh can reduce entry but also changes airflow and beneficial-insect access.",
    sourceKeys: ["UT_INSECTS"]
  },
  {
    name: "Fall armyworms",
    type: "Caterpillar",
    crops: "Corn, grasses and occasionally diverse vegetables",
    id: "Striped caterpillars; larger larvae often show an inverted pale Y on the head.",
    damage: "Rapid chewing/defoliation; can move in groups and damage whorls or seedlings.",
    now: ["Scout early because small larvae are easier to manage", "Hand-remove in small plots", "Inspect corn whorls and nearby grasses"],
    prevent: ["Control grassy weeds where appropriate", "Monitor seasonal outbreaks", "Encourage natural enemies"],
    treatment: "Bt and other caterpillar products work best on young larvae when labeled for the crop; large larvae are harder to control.",
    netNote: "Covers can protect small seedling beds but are impractical for tall corn.",
    sourceKeys: ["UT_INSECTS"]
  },
  {
    name: "European corn borer",
    type: "Moth larva / stem and ear borer",
    crops: "Corn, pepper and other hosts",
    id: "Larvae tunnel in stalks, tassels, ears or pepper fruit; frass may mark entry points.",
    damage: "Stem breakage, ear/fruit injury and entry sites for rot.",
    now: ["Remove infested stems/fruit", "Destroy crop residue after harvest", "Scout before larvae enter protected tunnels"],
    prevent: ["Timely residue management", "Rotate where practical", "Choose resistant crop traits/cultivars where relevant and appropriate"],
    treatment: "Once larvae tunnel deeply into stems, contact treatments become much less effective.",
    netNote: "Fine mesh is only practical on small plants before they outgrow the structure.",
    sourceKeys: ["UT_INSECTS"]
  },
  {
    name: "Pickleworms",
    type: "Moth larva / fruit borer",
    crops: "Cucumber, squash, cantaloupe and other cucurbits",
    id: "Larvae bore into blossoms, stems and fruit, leaving holes and frass.",
    damage: "Direct fruit loss and secondary rot.",
    now: ["Remove infested fruit/blossoms", "Scout flowers and young fruit", "Harvest promptly"],
    prevent: ["Use exclusion during vulnerable periods where pollination can still be managed", "Clean crop residue"],
    treatment: "Treatments must reach larvae before they bore deeply into protected tissue.",
    netNote: "Cucurbit pollination makes continuous exclusion complicated; hand pollination is an option for small covered plots.",
    sourceKeys: ["UT_INSECTS"]
  },
  {
    name: "Cowpea curculio",
    type: "Weevil / pod feeder",
    crops: "Cowpeas and southern peas",
    id: "Small dark weevils; adults puncture pods and larvae develop in seeds.",
    damage: "Scarred pods and damaged peas.",
    now: ["Harvest regularly", "Remove infested pods", "Do not leave mature infested peas in the field"],
    prevent: ["Destroy crop residue", "Rotate away from cowpeas where practical", "Manage volunteer hosts"],
    treatment: "Preventing adult pod feeding before egg-laying is more effective than trying to reach larvae inside seeds.",
    netNote: "Mesh may help small plantings but must be installed before adults arrive and managed around plant size.",
    sourceKeys: ["UT_INSECTS"]
  },
  {
    name: "Potato tuberworm",
    type: "Moth larva",
    crops: "Potato and related hosts",
    id: "Larvae mine leaves and tunnel tubers, especially tubers exposed near the soil surface or in storage.",
    damage: "Tuber tunnels reduce quality and invite decay.",
    now: ["Hill soil to keep tubers covered", "Remove infested tubers", "Store potatoes promptly and correctly"],
    prevent: ["Keep tubers covered with soil", "Remove cull piles/volunteers", "Use clean seed potatoes"],
    treatment: "Protecting tubers from exposure and preventing moth access are key.",
    netNote: "Row cover can help young crops but does not protect tubers exposed through cracked/shallow soil later.",
    sourceKeys: ["UT_INSECTS"]
  },
  {
    name: "Fire ants",
    type: "Stinging ant",
    crops: "Garden beds, orchards and greenhouse edges",
    id: "Aggressive ants associated with mounds; painful stings when nests are disturbed.",
    damage: "Main concern is human safety; ants can also tend honeydew-producing pests such as aphids.",
    now: ["Mark active mounds", "Keep children and vulnerable people away", "Address aphid/scale honeydew sources if ants are protecting them"],
    prevent: ["Monitor paths and work areas", "Avoid disturbing hidden mounds with bare hands"],
    treatment: "Use only ant baits/treatments labeled for the specific site, especially around edible crops.",
    netNote: "Netting has no meaningful role in mound control.",
    sourceKeys: ["UT_INSECTS"]
  },
  {
    name: "Japanese beetles",
    type: "Leaf/flower-feeding beetle",
    crops: "Grapes, berries, roses, fruit trees and many ornamentals",
    id: "Metallic green and copper adults often feeding in groups; leaves become skeletonized.",
    damage: "Defoliation and flower/fruit surface feeding, especially on favored plants.",
    now: ["Knock adults into soapy water in the cool morning on small plantings", "Prioritize young or heavily defoliated plants", "Avoid placing pheromone traps beside plants you are trying to protect"],
    prevent: ["Maintain plant vigor", "Use physical exclusion on small high-value plants when practical", "Accept moderate cosmetic feeding on established plants"],
    treatment: "Broad-spectrum sprays can harm pollinators and natural enemies; treat only when damage warrants it and avoid spraying open blooms.",
    netNote: "Fine mesh can protect small berries or young plants but must not block pollination during bloom.",
    sourceKeys: ["UT_FRUIT_PEST", "NCSU_IPM"]
  }

];

export const BUG_SEARCH_TERMS = [
  "good bugs", "beneficial insects", "bad bugs", "pests", "pollinators", "bees",
  "ladybug", "lacewing", "parasitoid", "aphids", "flea beetle", "cutworm", "thrips",
  "squash bug", "vine borer", "cucumber beetle", "hornworm", "cabbage worm",
  "whitefly", "mites", "stink bug", "slugs", "row cover", "netting", "IPM"
];
