export const PLANT_PROBLEMS = [
  {
    name: "Damping-off",
    category: "Fungal/oomycete complex",
    crops: "Seedlings of many vegetables and flowers; greenhouse/tent starts",
    symptoms: "Seeds rot before emergence or seedlings pinch/collapse at the soil line soon after emergence.",
    favors: "Persistently wet media, poor airflow, contaminated trays/media, dense sowing and cool stressful conditions.",
    lookalikes: "Drying injury, fertilizer/salt burn, mechanical stem injury.",
    now: ["Remove collapsed seedlings", "Let the media surface dry appropriately between irrigation", "Increase airflow without desiccating seedlings", "Do not reuse obviously contaminated wet media"],
    prevent: ["Use clean containers and quality seed-starting media", "Avoid overwatering", "Provide light/temperature that produce sturdy fast-growing seedlings", "Sanitize reusable equipment"],
    cure: "A collapsed seedling will not recover. Management is prevention and protecting unaffected seedlings.",
    sourceKeys: ["UT_DISEASE", "NCSU_DISEASE"]
  },
  {
    name: "Early blight of tomato",
    category: "Fungal disease",
    crops: "Tomato; also potato",
    symptoms: "Older leaves develop brown spots often with concentric 'target' rings; yellowing and defoliation can progress upward.",
    favors: "Warm humid weather, leaf wetness, infected debris and stressed plants.",
    lookalikes: "Septoria leaf spot, bacterial leaf spots, nutrient/stress-related lower-leaf yellowing.",
    now: ["Remove heavily infected lower leaves without stripping healthy canopy", "Avoid overhead irrigation late in the day", "Stake/trellis for airflow", "Mulch to reduce soil splash"],
    prevent: ["Rotate away from tomato-family crops where practical", "Remove infected residue", "Use healthy transplants", "Provide adequate fertility/water without excess nitrogen"],
    cure: "Fungicides are preventive/protective rather than a cure for dead tissue. If needed, consult the current Extension recommendation and product label for the crop.",
    sourceKeys: ["UT_DISEASE", "NCSU_PATH"]
  },
  {
    name: "Septoria leaf spot",
    category: "Fungal disease",
    crops: "Tomato",
    symptoms: "Numerous small circular leaf spots with tan/gray centers and darker margins, usually beginning on lower leaves.",
    favors: "Warm wet weather, splashing water and infected debris.",
    lookalikes: "Early blight and bacterial leaf spots.",
    now: ["Remove heavily infected lower foliage", "Keep leaves dry when possible", "Improve spacing/airflow", "Mulch soil surface"],
    prevent: ["Rotate", "Sanitation", "Trellis", "Water at soil level"],
    cure: "Existing lesions do not heal. Protect remaining foliage using cultural practices and, if warranted, a currently labeled fungicide.",
    sourceKeys: ["UT_DISEASE", "NCSU_PATH"]
  },
  {
    name: "Tomato bacterial spot",
    category: "Bacterial disease",
    crops: "Tomato and pepper",
    symptoms: "Small dark leaf and fruit spots; lesions may coalesce and cause leaf loss; fruit spots can become scabby.",
    favors: "Warm wet weather, splashing water, contaminated seed/transplants and handling wet foliage.",
    lookalikes: "Bacterial speck, Septoria, early blight, other leaf spots.",
    now: ["Avoid working plants while wet", "Remove severely affected plants if disease is spreading", "Sanitize tools between suspect plants", "Avoid saving seed from affected plants"],
    prevent: ["Start with clean seed/transplants", "Use resistant/tolerant cultivars when available", "Use drip irrigation", "Rotate and remove residue"],
    cure: "Bacterial diseases are difficult to cure once established. Protectant products have limits; confirm diagnosis and use only current labeled recommendations.",
    sourceKeys: ["UT_DISEASE", "NCSU_PATH"]
  },
  {
    name: "Tomato bacterial wilt",
    category: "Bacterial vascular disease",
    crops: "Tomato and other susceptible solanaceous plants",
    symptoms: "Rapid wilting of otherwise green foliage, often without the yellowing/leaf-spot pattern expected from foliar diseases.",
    favors: "Warm soils in infested sites; pathogen persists in soil in affected regions.",
    lookalikes: "Fusarium/Verticillium wilt, root injury, drought, waterlogging, southern blight.",
    now: ["Remove and discard infected plants and roots", "Do not compost suspect plants into vegetable beds", "Clean soil from tools/footwear before moving to uninfested areas"],
    prevent: ["Use nonhost rotation and resistant/rootstock options where appropriate", "Avoid moving infested soil", "Use clean transplants"],
    cure: "There is no practical curative spray for an infected plant; management focuses on sanitation, site avoidance/rotation and resistant material.",
    sourceKeys: ["NCSU_PATH", "NCSU_DISEASE"]
  },
  {
    name: "Fusarium wilt of tomato",
    category: "Fungal vascular disease",
    crops: "Tomato",
    symptoms: "Yellowing/wilting often begins on lower leaves and may affect one side; vascular tissue inside lower stem can discolor brown.",
    favors: "Warm soil and infested soil; susceptible cultivars.",
    lookalikes: "Bacterial wilt, Verticillium wilt, root rot, drought.",
    now: ["Remove severely affected plants", "Inspect stem vascular tissue and roots", "Do not move infested soil around the garden"],
    prevent: ["Choose cultivars with appropriate Fusarium resistance codes", "Rotate with nonhosts where practical", "Use clean media/transplants", "Consider resistant grafted rootstocks in recurring sites"],
    cure: "There is no home-garden foliar spray that cures a colonized vascular system.",
    sourceKeys: ["UT_DISEASE", "NCSU_PATH"]
  },
  {
    name: "Tomato anthracnose",
    category: "Fungal fruit rot",
    crops: "Tomato; especially ripe fruit",
    symptoms: "Sunken circular lesions develop on ripening fruit and enlarge in warm wet conditions.",
    favors: "Warm wet weather, splash dispersal and overripe fruit remaining in the garden.",
    lookalikes: "Other fruit rots, sunscald followed by secondary decay.",
    now: ["Harvest ripe fruit promptly", "Remove infected fruit", "Keep fruit off soil", "Avoid overhead wetting when possible"],
    prevent: ["Stake/cage", "Mulch", "Rotate", "Sanitation"],
    cure: "Remove affected fruit; protective management is aimed at uninfected fruit.",
    sourceKeys: ["UT_DISEASE"]
  },
  {
    name: "Late blight",
    category: "Oomycete disease",
    crops: "Tomato and potato",
    symptoms: "Rapidly expanding water-soaked/dark lesions on foliage and stems; fruit/tubers can rot; disease can advance extremely quickly in favorable weather.",
    favors: "Cool-to-mild wet weather and prolonged leaf wetness.",
    lookalikes: "Early blight, bacterial diseases, severe leaf scorch.",
    now: ["Treat a suspected case as urgent", "Photograph and seek Extension/diagnostic confirmation", "Remove severely infected material according to local guidance", "Avoid moving wet infected foliage through the garden"],
    prevent: ["Healthy planting material", "Good airflow", "Avoid unnecessary leaf wetness", "Monitor regional disease alerts when available"],
    cure: "Once a plant is heavily infected, rescue is unlikely. Fungicides are primarily preventive and timing-sensitive; use current Extension guidance.",
    sourceKeys: ["UT_DISEASE", "NCSU_PATH"]
  },
  {
    name: "Blossom-end rot",
    category: "Abiotic disorder — not infectious",
    crops: "Tomato, pepper, squash and related fruiting crops",
    symptoms: "Dark sunken leathery area at the blossom end of developing fruit.",
    favors: "Uneven water supply to roots, root injury, excess salts and conditions that disrupt calcium movement into rapidly growing fruit.",
    lookalikes: "Fruit rots and insect injury.",
    now: ["Remove badly affected fruit", "Keep root-zone moisture even", "Mulch", "Check irrigation distribution", "Avoid aggressive root cultivation"],
    prevent: ["Soil test before liming/fertilizing", "Maintain even moisture", "Avoid over-fertilizing", "Build a healthy root system"],
    cure: "Adding calcium blindly is not a reliable fix when soil calcium is already adequate; correct the water/root problem first.",
    sourceKeys: ["NCSU_DISEASE", "UT_MGMT"]
  },
  {
    name: "Powdery mildew on cucurbits",
    category: "Fungal disease",
    crops: "Squash, pumpkin, cucumber, melon",
    symptoms: "White powdery patches expand across leaves; older leaves are often affected first; severe infection reduces photosynthesis.",
    favors: "Dense canopies and conducive humidity/temperature; unlike many foliar diseases, free water on the leaf is not required for infection.",
    lookalikes: "Natural pale/silver leaf markings on some squash cultivars.",
    now: ["Confirm powdery growth rather than normal leaf pattern", "Remove the worst leaves only if canopy can spare them", "Improve airflow", "Harvest/maintain plant vigor"],
    prevent: ["Resistant cultivars", "Adequate spacing", "Sunlight and airflow", "Avoid excessive nitrogen"],
    cure: "Protectant fungicides can slow spread when started early; follow current Extension recommendations and labels. Dead leaf tissue will not recover.",
    sourceKeys: ["UT_DISEASE", "NCSU_PATH"]
  },
  {
    name: "Cucurbit downy mildew",
    category: "Oomycete disease",
    crops: "Cucumber, melon, squash and other cucurbits",
    symptoms: "Angular yellow-to-brown lesions bounded by veins; gray-purple sporulation may appear on leaf undersides in humid conditions.",
    favors: "High humidity/leaf wetness and movement of spores into the region.",
    lookalikes: "Angular leaf spot, nutrient problems, other foliar diseases.",
    now: ["Check leaf undersides", "Seek current regional/Extension reports if outbreak is suspected", "Remove severely damaged foliage if practical", "Avoid overhead irrigation"],
    prevent: ["Resistant cultivars where available", "Airflow", "Timely scouting"],
    cure: "Management is preventative and weather-dependent; home remedies are unreliable. Use current crop-specific Extension guidance.",
    sourceKeys: ["NCSU_PATH", "UT_DISEASE"]
  },
  {
    name: "Cucurbit bacterial wilt",
    category: "Bacterial disease — insect vectored",
    crops: "Cucumber and susceptible cucurbits",
    symptoms: "Individual leaves/vines wilt, then larger portions collapse; often associated with cucumber beetle feeding.",
    favors: "Presence of vector cucumber beetles and susceptible crops.",
    lookalikes: "Squash vine borer, drought, root rot, stem injury.",
    now: ["Check for cucumber beetles and stem borer signs", "Remove infected plants", "Manage beetle movement among remaining susceptible plants"],
    prevent: ["Exclude cucumber beetles early with row cover", "Open/remove covers for pollination at flowering", "Use resistant/tolerant crop choices where available"],
    cure: "The infected vascular system cannot be cured; vector prevention is the main strategy.",
    sourceKeys: ["UT_INSECTS", "NCSU_PATH"]
  },
  {
    name: "Gummy stem blight / black rot complex",
    category: "Fungal disease",
    crops: "Cucurbits",
    symptoms: "Leaf lesions and stem cankers that may exude gummy material; fruit can develop black rot.",
    favors: "Warm wet conditions, infected seed/debris and leaf wetness.",
    lookalikes: "Mechanical stem wounds, bacterial diseases, other cucurbit cankers.",
    now: ["Remove badly infected plants/debris", "Reduce leaf wetness", "Sanitize tools", "Avoid handling wet plants"],
    prevent: ["Clean seed/transplants", "Rotation", "Airflow", "Sanitation"],
    cure: "Protective fungicides may be part of management after diagnosis; established cankers will not heal because of spraying.",
    sourceKeys: ["NCSU_PATH", "UT_DISEASE"]
  },
  {
    name: "Squash/cucurbit viruses",
    category: "Viral disease",
    crops: "Squash, pumpkin, cucumber, melon",
    symptoms: "Mosaic/mottled leaves, distortion, stunting and misshapen or color-broken fruit.",
    favors: "Infected seed/plant material for some viruses and insect vectors such as aphids or beetles depending on virus.",
    lookalikes: "Herbicide injury, nutrient problems, mite/thrips injury.",
    now: ["Remove strongly symptomatic plants after confirming likely virus", "Control nearby weeds that can act as reservoirs", "Do not propagate from symptomatic plants"],
    prevent: ["Resistant cultivars", "Clean seed/transplants", "Vector and weed management"],
    cure: "There is no pesticide that cures a virus already inside a plant.",
    sourceKeys: ["UT_DISEASE", "NCSU_PATH"]
  },
  {
    name: "Brassica black rot",
    category: "Bacterial disease",
    crops: "Cabbage, broccoli, kale, collards and other brassicas",
    symptoms: "Yellow V-shaped lesions often begin at leaf margins; veins may darken.",
    favors: "Warm wet weather, splash, infected seed/transplants and handling wet plants.",
    lookalikes: "Nutrient stress, downy mildew, other leaf spots.",
    now: ["Remove badly infected plants", "Avoid working wet foliage", "Sanitize tools", "Keep irrigation off leaves where practical"],
    prevent: ["Disease-free seed/transplants", "Rotation", "Destroy infected residues", "Control crucifer weeds"],
    cure: "Once systemic infection is established, removal is generally more effective than trying to cure the plant.",
    sourceKeys: ["UT_DISEASE", "NCSU_PATH"]
  },
  {
    name: "Brassica Alternaria leaf spot",
    category: "Fungal disease",
    crops: "Brassicas",
    symptoms: "Dark circular spots, often with concentric rings, on leaves and heads.",
    favors: "Wet foliage, infected seed/debris and moderate-to-warm conditions.",
    lookalikes: "Black rot, other leaf spots.",
    now: ["Remove severely spotted leaves", "Improve airflow", "Avoid overhead watering"],
    prevent: ["Clean seed", "Rotation", "Residue management", "Adequate spacing"],
    cure: "Protect remaining healthy tissue; existing lesions will remain.",
    sourceKeys: ["UT_DISEASE"]
  },
  {
    name: "Brassica downy mildew",
    category: "Oomycete disease",
    crops: "Brassicas",
    symptoms: "Yellow angular areas above and gray/white growth below leaves, especially in cool humid conditions.",
    favors: "Cool moist weather and prolonged humidity/leaf wetness.",
    lookalikes: "Nutrient stress, white rust and other foliar diseases.",
    now: ["Improve airflow", "Water early at soil level", "Remove heavily affected material"],
    prevent: ["Resistant cultivars where available", "Rotation", "Sanitation"],
    cure: "Use current Extension recommendations if disease pressure warrants a labeled protectant.",
    sourceKeys: ["UT_DISEASE"]
  },
  {
    name: "Bean anthracnose",
    category: "Fungal disease",
    crops: "Beans",
    symptoms: "Dark sunken lesions on pods/stems and vein-associated lesions on leaves; infected seed can spread disease.",
    favors: "Cool-to-moderate wet weather and working wet plants.",
    lookalikes: "Bacterial blights and mechanical injury.",
    now: ["Do not work among wet bean plants", "Remove badly affected plants/pods", "Do not save seed from diseased plants"],
    prevent: ["Use disease-free seed", "Rotate", "Airflow", "Residue sanitation"],
    cure: "Established infections are managed by sanitation and protecting new growth, not by repairing lesions.",
    sourceKeys: ["UT_DISEASE", "NCSU_PATH"]
  },
  {
    name: "Bean rust",
    category: "Fungal disease",
    crops: "Beans",
    symptoms: "Rust-colored pustules, often on leaf undersides, leading to yellowing and defoliation.",
    favors: "Moderate temperatures and leaf wetness/high humidity.",
    lookalikes: "Other leaf spots and insect stippling.",
    now: ["Remove badly affected leaves/plants where practical", "Increase airflow", "Avoid overhead irrigation"],
    prevent: ["Resistant varieties", "Rotation", "Residue management"],
    cure: "Preventive fungicides may help when disease is identified early; follow current labels and Extension guidance.",
    sourceKeys: ["UT_DISEASE"]
  },
  {
    name: "Bean bacterial blights",
    category: "Bacterial disease",
    crops: "Beans",
    symptoms: "Water-soaked then brown leaf lesions, often with yellow margins; pods can spot.",
    favors: "Warm wet weather, seedborne inoculum and splash.",
    lookalikes: "Anthracnose and other leaf spots.",
    now: ["Avoid handling wet foliage", "Remove severely affected plants", "Sanitize tools"],
    prevent: ["Certified/disease-free seed", "Rotation", "Avoid overhead irrigation"],
    cure: "Bacterial infections are difficult to cure; prevention and sanitation carry most of the value.",
    sourceKeys: ["UT_DISEASE"]
  },
  {
    name: "Potato common scab",
    category: "Soilborne bacterial disease",
    crops: "Potato",
    symptoms: "Rough corky/scabby lesions on tuber skin.",
    favors: "Infested soil and conditions favorable to the pathogen; soil pH is an important management factor.",
    lookalikes: "Mechanical skin injury and other tuber diseases.",
    now: ["Affected tubers may still be usable after trimming if otherwise sound; do not use diseased tubers as seed", "Record the bed/site"],
    prevent: ["Use certified seed potatoes", "Manage soil pH according to crop-specific recommendations rather than broadly liming", "Rotate"],
    cure: "There is no way to remove scab from a developing tuber after infection; management is preventive.",
    sourceKeys: ["UT_DISEASE"]
  },
  {
    name: "Sweet potato black rot",
    category: "Fungal disease",
    crops: "Sweet potato",
    symptoms: "Dark sunken lesions on storage roots and possible vine/root infection.",
    favors: "Infected slips/roots, contaminated soil/equipment and storage conditions.",
    lookalikes: "Other storage rots and mechanical damage.",
    now: ["Discard badly affected roots", "Sanitize storage/contact surfaces", "Do not propagate from diseased roots"],
    prevent: ["Use healthy slips/roots", "Rotate", "Cure/store roots correctly"],
    cure: "Infected roots are not cured in storage; prevention and clean planting material are key.",
    sourceKeys: ["UT_DISEASE"]
  },
  {
    name: "Sweet potato scurf",
    category: "Fungal surface disease",
    crops: "Sweet potato",
    symptoms: "Superficial dark brown/black skin discoloration on storage roots.",
    favors: "Infected planting material and contaminated soil.",
    lookalikes: "Black rot, soil staining and skin injury.",
    now: ["Separate affected roots from seed stock", "Clean equipment/containers"],
    prevent: ["Use clean planting stock", "Rotation"],
    cure: "Surface discoloration does not disappear after harvest; prevent new infections in future crops.",
    sourceKeys: ["UT_DISEASE"]
  },
  {
    name: "Root-knot nematodes",
    category: "Plant-parasitic nematode",
    crops: "Many vegetables",
    symptoms: "Stunting/wilting despite water, nutrient-like symptoms and characteristic galls/knots on roots.",
    favors: "Infested soil and susceptible crops; often worse in warm soils.",
    lookalikes: "Root rot, compacted soil, drought and nutrient deficiency.",
    now: ["Dig an entire root system and inspect", "Submit a soil/root sample for diagnosis when uncertain", "Remove heavily affected roots"],
    prevent: ["Resistant varieties", "Nonhost rotation/cover crops chosen for the nematode species", "Avoid moving infested soil"],
    cure: "There is no simple rescue treatment for a heavily galled plant; long-term population management is required.",
    sourceKeys: ["UT_DISEASE", "NCSU_DIAG"]
  },
  {
    name: "Botrytis gray mold",
    category: "Fungal disease",
    crops: "Many crops; especially greenhouse/high-tunnel flowers, tomatoes and tender growth",
    symptoms: "Soft brown lesions with fuzzy gray sporulation on flowers, fruit, leaves or wounded tissue.",
    favors: "High humidity, condensation, dead plant tissue, crowded canopies and cool-to-moderate temperatures.",
    lookalikes: "Other fruit rots and senescent tissue.",
    now: ["Remove infected/dead tissue promptly", "Vent and circulate air", "Reduce overnight condensation", "Avoid wetting foliage"],
    prevent: ["Sanitation", "Spacing/pruning for airflow", "Morning irrigation", "Avoid leaving fallen petals/leaves in dense crops"],
    cure: "Environmental correction is critical; fungicide-only programs fail when humidity and dead tissue remain unmanaged.",
    sourceKeys: ["NCSU_PATH", "UT_DISEASE"]
  },
  {
    name: "Tomato leaf mold (protected culture)",
    category: "Fungal disease",
    crops: "Greenhouse/high-tunnel tomato",
    symptoms: "Yellow patches on upper leaf surfaces with olive-green/brown velvety growth beneath.",
    favors: "High relative humidity and poor air circulation.",
    lookalikes: "Other leaf spots, nutrient stress.",
    now: ["Vent", "Increase air circulation", "Remove affected leaves carefully", "Lower prolonged humidity"],
    prevent: ["Resistant varieties", "Adequate spacing", "Humidity management", "Sanitation"],
    cure: "Control requires changing the greenhouse environment as well as protecting clean foliage.",
    sourceKeys: ["NCSU_PATH"]
  },
  {
    name: "Greenhouse root rot / Pythium-type problems",
    category: "Oomycete/root disease complex",
    crops: "Seedlings, hydroponic/soilless and container crops",
    symptoms: "Poor roots, brown/sloughing roots, stunting, wilt despite wet media.",
    favors: "Saturated media, low root oxygen, contaminated irrigation/equipment and stressful root temperatures.",
    lookalikes: "Fertilizer salt injury, drought after root loss, mechanical root damage.",
    now: ["Stop chronic saturation", "Inspect roots", "Remove severely affected plants", "Clean shared reservoirs/equipment as appropriate"],
    prevent: ["Well-drained media", "Correct irrigation frequency", "Clean containers", "Do not let contaminated runoff move between plants"],
    cure: "Root systems already destroyed will not be restored by foliar spraying; correct the root environment and prevent spread.",
    sourceKeys: ["NCSU_PATH", "NCSU_DIAG"]
  },
  {
    name: "Herbicide injury",
    category: "Abiotic — not infectious",
    crops: "Many vegetables, especially tomatoes and beans",
    symptoms: "Twisted/cupped leaves, strapping, abnormal new growth, distorted stems or sudden uniform symptoms after exposure.",
    favors: "Spray drift, contaminated compost/manure/hay, sprayer carryover or volatile herbicides.",
    lookalikes: "Viruses, mites, nutrient disorders and heat stress.",
    now: ["Stop suspected exposure", "Document pattern and nearby applications/material sources", "Do not compost severely contaminated plant material back into food beds until source is understood"],
    prevent: ["Know the history of manure/compost/hay", "Use dedicated or meticulously cleaned sprayers", "Avoid spraying herbicides in drift-prone conditions"],
    cure: "There is no antidote. Mildly affected plants may outgrow exposure; severe injury may require replacement.",
    sourceKeys: ["NCSU_DIAG"]
  },
  {
    name: "Sunscald / heat injury",
    category: "Abiotic — not infectious",
    crops: "Tomato, pepper and exposed fruits/leaves",
    symptoms: "Bleached, papery or tan areas on sun-exposed tissue, often after sudden canopy loss or transplant exposure.",
    favors: "Extreme sun/heat and abrupt transition from shade/protection to full sun.",
    lookalikes: "Fruit rots and chemical burn.",
    now: ["Protect remaining canopy", "Use temporary shade during extreme transition", "Harvest damaged ripe fruit before secondary rot"],
    prevent: ["Harden transplants gradually", "Avoid excessive pruning", "Maintain irrigation"],
    cure: "Dead/scalded tissue does not recover; prevent additional exposure.",
    sourceKeys: ["NCSU_DIAG", "UT_HOME"]
  },
  {
    name: "Edema / water imbalance",
    category: "Abiotic — not infectious",
    crops: "Greenhouse tomatoes, peppers, houseplants and other protected crops",
    symptoms: "Corky bumps or blisters on leaves when roots absorb water faster than leaves can transpire.",
    favors: "High humidity, wet roots, cool conditions and low airflow/light.",
    lookalikes: "Mites, bacterial spots and chemical injury.",
    now: ["Reduce chronic media saturation", "Increase safe airflow", "Improve light/temperature balance"],
    prevent: ["Irrigate based on root-zone need", "Vent protected structures", "Avoid keeping roots saturated overnight"],
    cure: "Existing corky tissue remains; new growth should improve after environment is corrected.",
    sourceKeys: ["NCSU_DIAG"]
  },
  {
    name: "Fire blight of apple and pear",
    category: "Bacterial fruit-tree disease",
    crops: "Apple, pear and susceptible relatives",
    symptoms: "Blossoms and shoot tips suddenly blacken and wilt; shoots often bend into a characteristic shepherd's-crook shape; cankers may form on limbs.",
    favors: "Warm wet conditions during bloom, vigorous succulent growth and susceptible cultivars.",
    lookalikes: "Frost injury, shoot breakage, other cankers.",
    now: ["Confirm symptoms before pruning", "Remove infected shoots/cankers during appropriate dry conditions using current Extension pruning guidance", "Disinfect tools when recommended", "Avoid excess nitrogen that drives very succulent growth"],
    prevent: ["Choose resistant/tolerant cultivars where practical", "Manage vigor", "Use proper pruning and sanitation", "Follow bloom-period disease forecasts/recommendations if managing high-value trees"],
    cure: "Dead shoots do not recover. Antibiotic use in fruit trees is tightly label- and timing-dependent; home growers should follow current Extension guidance rather than improvising.",
    sourceKeys: ["UT_FRUIT_PEST"]
  },
  {
    name: "Apple scab",
    category: "Fungal fruit-tree disease",
    crops: "Apple and crabapple",
    symptoms: "Olive-green to dark velvety leaf spots; fruit may develop dark scabby cracked lesions.",
    favors: "Cool wet spring weather and infected fallen leaves.",
    lookalikes: "Frog-eye leaf spot, cedar-apple rust, cosmetic fruit russeting.",
    now: ["Remove badly infected fallen leaves/fruit", "Improve canopy airflow with correct pruning", "Avoid prolonged leaf wetness where irrigation is used"],
    prevent: ["Plant scab-resistant cultivars", "Sanitation of fallen leaves", "Open canopy and full-sun siting"],
    cure: "Fungicides are mostly preventive and growth-stage/weather timed; established scabs will not disappear.",
    sourceKeys: ["UT_FRUIT_PEST"]
  },
  {
    name: "Cedar-apple rust",
    category: "Fungal fruit-tree disease",
    crops: "Apple/crabapple with juniper/cedar alternate hosts",
    symptoms: "Bright yellow-orange spots on apple leaves/fruit; orange gelatinous spore horns may appear on galls of nearby junipers during wet spring weather.",
    favors: "Presence of both susceptible hosts and wet spring conditions.",
    lookalikes: "Apple scab and other leaf spots.",
    now: ["Confirm the distinctive orange/yellow pattern", "Remove nearby cedar galls if practical on a small property", "Maintain tree vigor"],
    prevent: ["Choose resistant apple cultivars", "Understand the alternate-host life cycle", "Use preventive fungicide only when justified and timed according to Extension guidance"],
    cure: "Removing leaf spots after infection does not cure them; management protects future/new tissue and reduces the life cycle.",
    sourceKeys: ["UT_FRUIT_PEST"]
  },
  {
    name: "Peach brown rot",
    category: "Fungal fruit rot",
    crops: "Peach, plum, cherry and other stone fruits",
    symptoms: "Rapid brown soft rot on ripening fruit, often with tan spore masses; shriveled 'mummy' fruit can remain on trees.",
    favors: "Warm wet weather, fruit wounds and infected blossoms/twigs/mummified fruit.",
    lookalikes: "Other fruit rots and insect-damaged fruit with secondary decay.",
    now: ["Remove rotten and mummified fruit", "Harvest ripe fruit promptly", "Reduce fruit injury from insects and handling"],
    prevent: ["Sanitation", "Pruning for airflow", "Fruit thinning to reduce contact", "Preventive disease program when warranted"],
    cure: "Rotten fruit cannot be restored. Protect uninfected fruit and remove inoculum.",
    sourceKeys: ["UT_FRUIT_PEST"]
  },
  {
    name: "Peach leaf curl",
    category: "Fungal fruit-tree disease",
    crops: "Peach and nectarine",
    symptoms: "Young spring leaves become thickened, puckered, curled and red/purple before turning pale and dropping.",
    favors: "Cool wet conditions during bud swell/early leaf development.",
    lookalikes: "Aphid distortion, herbicide injury.",
    now: ["Once symptoms are visible in spring, maintain tree vigor and water appropriately", "Remove fallen diseased leaves if practical"],
    prevent: ["A correctly timed dormant-season fungicide is the key control where needed", "Follow current Extension timing and label"],
    cure: "Spring sprays after obvious leaf curl appears are generally too late to cure that season's infected leaves.",
    sourceKeys: ["UT_FRUIT_PEST"]
  },
  {
    name: "Black knot of plum and cherry",
    category: "Fungal fruit-tree disease",
    crops: "Plum, cherry and related Prunus",
    symptoms: "Hard elongated black swollen knots develop on twigs and branches and enlarge over time.",
    favors: "Susceptible trees and wet spring infection periods; nearby infected wild/ornamental Prunus can be inoculum sources.",
    lookalikes: "Crown gall, normal callus tissue, other cankers.",
    now: ["Prune infected branches well below visible knots during appropriate conditions", "Remove prunings from the area", "Inspect nearby susceptible Prunus"],
    prevent: ["Choose less-susceptible cultivars", "Sanitation", "Maintain open canopy"],
    cure: "Existing woody knots must be physically removed with affected wood; fungicides are preventive supplements, not knot removers.",
    sourceKeys: ["UT_FRUIT_PEST"]
  },
  {
    name: "Grape black rot",
    category: "Fungal fruit disease",
    crops: "Bunch grapes",
    symptoms: "Tan-to-reddish leaf spots with dark margins; berries develop brown spots then shrivel into black wrinkled mummies.",
    favors: "Warm wet spring/summer weather and overwintered infected mummified fruit/canes.",
    lookalikes: "Other grape fruit rots and leaf spots.",
    now: ["Remove mummified clusters and infected debris", "Prune/train vines for sunlight and airflow", "Do not leave infected fruit hanging into the next season"],
    prevent: ["Sanitation is essential", "Open canopy", "Preventive fungicide program timed to susceptible growth stages where needed"],
    cure: "Shriveled infected berries will not recover. Management protects new tissue and breaks the disease cycle.",
    sourceKeys: ["UT_GRAPE_ROT", "UT_FRUIT_PEST"]
  },
  {
    name: "Grape powdery mildew",
    category: "Fungal fruit disease",
    crops: "Grapes",
    symptoms: "White-gray powdery growth on leaves, shoots or fruit; infected berries may crack or fail to ripen normally.",
    favors: "Humid conditions and dense shaded canopies; free-standing water is not required the way it is for many other foliar pathogens.",
    lookalikes: "Spray residue and downy mildew.",
    now: ["Improve canopy airflow/light", "Remove heavily infected clusters if they are no longer marketable", "Confirm powdery growth"],
    prevent: ["Canopy management", "Disease-resistant cultivars where appropriate", "Preventive fungicide timing"],
    cure: "Existing damaged berries do not become sound again; early protection is much more effective than late rescue.",
    sourceKeys: ["UT_FRUIT_PEST"]
  },
  {
    name: "Strawberry gray mold (Botrytis fruit rot)",
    category: "Fungal fruit rot",
    crops: "Strawberry",
    symptoms: "Flowers or berries develop brown rot and fuzzy gray spores, often beginning where dead petals or injured tissue remain.",
    favors: "Cool-to-moderate wet/humid bloom and harvest weather, dense canopy and fruit touching damp material.",
    lookalikes: "Leather rot and other strawberry fruit rots.",
    now: ["Pick and remove rotten berries frequently", "Harvest carefully to avoid injury", "Improve airflow and keep fruit off wet soil"],
    prevent: ["Appropriate spacing", "Clean straw/mulch", "Drip irrigation", "Bloom-time disease management when warranted"],
    cure: "Rotten berries should be removed; fungicides protect flowers/fruit before severe infection rather than restoring rotted fruit.",
    sourceKeys: ["UT_FRUIT_PEST"]
  },
  {
    name: "Blackberry and raspberry cane diseases",
    category: "Fungal cane-disease complex",
    crops: "Blackberries and raspberries",
    symptoms: "Cane spots/cankers, dieback, weak fruiting laterals or lesions associated with wounds.",
    favors: "Dense plantings, wet foliage, old infected canes and wounds.",
    lookalikes: "Winter injury, crown/root disease, cane-borer insect injury.",
    now: ["Determine whether decline begins at a cane lesion, crown or borer entry point", "Remove dead/diseased canes at the appropriate time", "Remove pruning debris"],
    prevent: ["Maintain narrow rows and airflow", "Remove spent floricanes promptly after harvest when recommended", "Avoid unnecessary cane injury"],
    cure: "Dead cane tissue cannot be revived; sanitation and protecting healthy replacement canes are the goal.",
    sourceKeys: ["UT_FRUIT_PEST"]
  },
  {
    name: "Blueberry mummy berry",
    category: "Fungal fruit disease",
    crops: "Blueberry",
    symptoms: "Shoot/flower blight can occur early; infected berries later become pale, shriveled and hard 'mummies' that fall to the ground.",
    favors: "Cool wet spring conditions and overwintered mummified berries beneath bushes.",
    lookalikes: "Frost injury, Botrytis blossom blight, drought-shriveled berries.",
    now: ["Remove visible mummified berries", "Rake or cover old mummies beneath bushes according to current guidance", "Document whether early shoot blight preceded fruit symptoms"],
    prevent: ["Sanitation beneath bushes", "Airflow", "Appropriate cultivar/site selection", "Preventive disease program if the problem recurs"],
    cure: "Affected berries will not recover; management focuses on reducing overwintering inoculum and protecting next season's bloom.",
    sourceKeys: ["UT_FRUIT_PEST"]
  }

];

export const DISEASE_SEARCH_TERMS = [
  "plant disease", "tomato disease", "cucumber disease", "squash disease", "pepper disease",
  "blight", "wilt", "powdery mildew", "downy mildew", "black rot", "anthracnose",
  "bacterial spot", "bacterial wilt", "Fusarium", "Septoria", "Botrytis", "root rot",
  "damping off", "greenhouse disease", "blossom end rot", "virus", "nematode",
  "herbicide injury", "sunscald", "edema", "apple", "pear", "fire blight", "apple scab", "cedar apple rust", "peach", "brown rot", "leaf curl", "plum", "cherry", "black knot", "grape", "black rot", "strawberry", "blackberry", "raspberry", "blueberry"
];
