export const YEAR_ROUND_MONTHS = [
  {month:'January', focus:'Plan, protect, propagate', outdoor:['Review last season and order seed before popular cultivars sell out.','Inspect stored roots, bulbs and produce; remove rot promptly.','On workable days, repair beds, trellises and drainage without compacting saturated soil.'], indoor:['Start slow-growing herbs and selected onions/leeks indoors when your cultivar schedule supports it.','Clean lights, fans, trays and irrigation equipment before spring propagation ramps up.'], protected:['Vent greenhouses on sunny days even in winter; humidity and condensation can drive disease.','Use row cover/cold frames as temperature buffers, not magic frost-proofing.'], reminders:['Seed inventory','Soil-test planning','Greenhouse sanitation']},
  {month:'February', focus:'Start the spring engine', outdoor:['Prepare cool-season beds only when soil is workable, not wet and plastic.','Direct-sow hardy cool crops as local conditions allow and keep protection ready.'], indoor:['Start brassicas and other transplant crops based on target outdoor date.','Pot up seedlings before they become root-bound; begin gentle airflow.'], protected:['Use cold frames/low tunnels to harden plants gradually.','Watch sunny-day overheating under plastic or glass.'], reminders:['Start spring transplants','Check row-cover supplies','Recheck drainage']},
  {month:'March', focus:'Cool-season production', outdoor:['Plant successive rounds of cool-season vegetables instead of one huge sowing.','Mulch after soil begins warming and beds are prepared.','Scout slugs, flea beetles, aphids and damping-off conditions early.'], indoor:['Keep warm-season seedlings under strong light; avoid rushing tender plants outside.'], protected:['Open protection for ventilation and pollinator access when crops flower.'], reminders:['Succession sowing','Scout cool-season pests','Harden seedlings']},
  {month:'April', focus:'Transition carefully', outdoor:['Continue cool crops while preparing warm-season beds.','Use actual forecast lows and soil conditions—not the calendar alone—for tender transplants.','Set trellises before vines become difficult to handle.'], indoor:['Harden tomatoes, peppers and other warm-season transplants over several days.'], protected:['Protect tender plants during late cold snaps; ventilate aggressively on warm sunny days.'], reminders:['Watch frost risk','Install trellises','Begin warm-season succession plan']},
  {month:'May', focus:'Warm-season establishment', outdoor:['Transplant warm-season crops when forecast and soil conditions are suitable.','Mulch, stake and set irrigation before plants become large.','Begin regular scouting at least weekly.'], indoor:['Use grow tents for starts, specialty crops or propagation—not as proof a plant is outdoor-hardy.'], protected:['Use shade/ventilation as greenhouse heat climbs.'], reminders:['Plant warm crops','Mulch and stake','Weekly scouting']},
  {month:'June', focus:'Water, train, scout', outdoor:['Water deeply and consistently based on soil moisture and weather, not habit alone.','Train vines and tomatoes; harvest frequently to keep plants productive.','Scout disease after warm, humid or rainy stretches.'], indoor:['Keep airflow high and watch root-zone temperature in tents.'], protected:['Manage humidity, shade and ventilation; greenhouse heat can exceed outdoor temperatures quickly.'], reminders:['Irrigation check','Disease scouting','Harvest rhythm']},
  {month:'July', focus:'Protect summer crops and start fall', outdoor:['Prioritize irrigation timing, mulch and heat stress management.','Start selected fall brassicas and other cool-season crops while summer harvest is still active.','Remove badly diseased residues instead of composting uncertain material.'], indoor:['Use propagation space for fall transplants.'], protected:['Shade and ventilate; inspect spider mites, whiteflies and thrips.'], reminders:['Start fall seedlings','Heat protection','Pest scouting']},
  {month:'August', focus:'Build the fall garden', outdoor:['Transplant or direct-sow fall crops in waves; provide temporary shade if heat is severe.','Keep summer crops producing while opening space for fall succession.','Watch rainfall trends before cultivating or seeding.'], indoor:['Continue fall starts and backup transplants.'], protected:['Prepare covers and tunnels before the first urgent cold forecast.'], reminders:['Fall planting','Succession round 2','Order row cover']},
  {month:'September', focus:'Cool-season reset', outdoor:['Plant fall greens, roots and brassicas according to days-to-maturity and expected cold.','Reduce irrigation as weather cools, but do not let new seedings dry out.','Clean spent warm-season crops and diseased material.'], indoor:['Take cuttings or move tender specialty plants indoors before cold damage.'], protected:['Inspect plastic, clips, anchors and venting before autumn storms.'], reminders:['Plant fall crops','Preserve/harvest summer crops','Inspect season-extension gear']},
  {month:'October', focus:'Extend rather than stop', outdoor:['Use frost-tolerant crops and protection to keep harvesting.','Plant cover crops where beds are finished when timing permits.','Add compost or mulch without burying crowns or creating saturated beds.'], indoor:['Restart herbs/greens under lights if desired.'], protected:['Close protection before cold nights, then reopen/vent when temperatures rebound.'], reminders:['Frost protection','Cover crop','Bring tender plants in']},
  {month:'November', focus:'Winterize and keep harvesting', outdoor:['Harvest hardy crops and protect roots/soil with appropriate mulch.','Drain or protect irrigation components that can freeze.','Record which beds held water or suffered erosion.'], indoor:['Grow microgreens, herbs or leafy crops under sufficient light if you want winter production.'], protected:['Monitor nighttime lows and daytime humidity; protection still needs ventilation.'], reminders:['Winterize irrigation','Mulch/protect','Record season notes']},
  {month:'December', focus:'Observe, maintain, learn', outdoor:['Harvest protected hardy crops when conditions permit.','Avoid repeated traffic on frozen/thawing or saturated beds.'], indoor:['Maintain indoor crops with disciplined watering, airflow and sanitation.'], protected:['Check snow/wind loads and secure covers; vent on warm sunny days.'], reminders:['Equipment maintenance','Seed list','Review garden records']}
];

export const YEAR_ROUND_SYSTEMS = [
  {title:'Outdoor beds', text:'Use hardy crops, succession planting, mulch, crop rotation and season extension. Zone 7a/7b still has real frost and freeze risk.'},
  {title:'Low tunnels & row cover', text:'Useful for frost buffering and insect exclusion, but temperature, ventilation and pollinator access must be managed.'},
  {title:'Cold frames', text:'Excellent shoulder-season tools. Vent manually or automatically on sunny days to prevent overheating.'},
  {title:'Greenhouse', text:'Adds protection but creates its own heat, humidity, disease and pollination problems. It is not automatically frost-free.'},
  {title:'Indoor grow tent', text:'Best for propagation and controlled crops year-round. Strong light, airflow, sanitation and root-zone management matter more than outdoor hardiness.'},
  {title:'Storage & preservation', text:'Year-round food also comes from curing, freezing, canning, drying and storing crops—not only keeping plants alive twelve months.'}
];
