// 130+ crops commonly grown in Northeast Tennessee (Zone 6b/7a), organized
// by category with the season each one typically goes in the ground.
export const CROPS = [
  { name: "Slicing Tomatoes", category: "Vegetables", season: "Late Spring" },
  { name: "Cherry Tomatoes", category: "Vegetables", season: "Late Spring" },
  { name: "Roma / Paste Tomatoes", category: "Vegetables", season: "Late Spring" },
  { name: "Bell Peppers", category: "Vegetables", season: "Late Spring" },
  { name: "Jalapeño Peppers", category: "Vegetables", season: "Late Spring" },
  { name: "Banana Peppers", category: "Vegetables", season: "Late Spring" },
  { name: "Poblano Peppers", category: "Vegetables", season: "Late Spring" },
  { name: "Habanero Peppers", category: "Vegetables", season: "Late Spring" },
  { name: "Cayenne Peppers", category: "Vegetables", season: "Late Spring" },
  { name: "Eggplant", category: "Vegetables", season: "Late Spring" },
  { name: "Okra", category: "Vegetables", season: "Late Spring" },
  { name: "Slicing Cucumbers", category: "Vegetables", season: "Late Spring" },
  { name: "Pickling Cucumbers", category: "Vegetables", season: "Late Spring" },
  { name: "Zucchini", category: "Vegetables", season: "Late Spring" },
  { name: "Yellow Summer Squash", category: "Vegetables", season: "Late Spring" },
  { name: "Butternut Squash", category: "Vegetables", season: "Late Spring" },
  { name: "Acorn Squash", category: "Vegetables", season: "Late Spring" },
  { name: "Spaghetti Squash", category: "Vegetables", season: "Late Spring" },
  { name: "Pumpkins", category: "Vegetables", season: "Late Spring" },
  { name: "Watermelon", category: "Vegetables", season: "Late Spring" },
  { name: "Cantaloupe", category: "Vegetables", season: "Late Spring" },
  { name: "Honeydew Melon", category: "Vegetables", season: "Late Spring" },
  { name: "Bush Green Beans", category: "Vegetables", season: "Late Spring" },
  { name: "Pole Green Beans", category: "Vegetables", season: "Late Spring" },
  { name: "Lima Beans", category: "Vegetables", season: "Late Spring" },
  { name: "Southern Peas (Field Peas)", category: "Vegetables", season: "Summer" },
  { name: "Edamame (Soybeans)", category: "Vegetables", season: "Late Spring" },
  { name: "Sweet Corn", category: "Vegetables", season: "Late Spring" },
  { name: "Popcorn", category: "Vegetables", season: "Late Spring" },
  { name: "Peanuts", category: "Vegetables", season: "Late Spring" },
  { name: "Tomatillos", category: "Vegetables", season: "Late Spring" },
  { name: "Ground Cherries", category: "Vegetables", season: "Late Spring" },
  { name: "Sweet Potatoes", category: "Vegetables", season: "Late Spring" },
  { name: "Irish Potatoes", category: "Root Vegetables & Alliums", season: "Early Spring" },
  { name: "Carrots", category: "Root Vegetables & Alliums", season: "Early Spring" },
  { name: "Beets", category: "Root Vegetables & Alliums", season: "Early Spring" },
  { name: "Radishes", category: "Root Vegetables & Alliums", season: "Early Spring" },
  { name: "Daikon Radish", category: "Root Vegetables & Alliums", season: "Fall" },
  { name: "Turnips", category: "Root Vegetables & Alliums", season: "Early Spring" },
  { name: "Rutabaga", category: "Root Vegetables & Alliums", season: "Fall" },
  { name: "Parsnips", category: "Root Vegetables & Alliums", season: "Early Spring" },
  { name: "Onions (from sets)", category: "Root Vegetables & Alliums", season: "Early Spring" },
  { name: "Onions (from seed)", category: "Root Vegetables & Alliums", season: "Late Winter" },
  { name: "Sweet Onions", category: "Root Vegetables & Alliums", season: "Early Spring" },
  { name: "Garlic", category: "Root Vegetables & Alliums", season: "Dormant Season" },
  { name: "Shallots", category: "Root Vegetables & Alliums", season: "Dormant Season" },
  { name: "Leeks", category: "Root Vegetables & Alliums", season: "Late Winter" },
  { name: "Green Onions / Scallions", category: "Root Vegetables & Alliums", season: "Early Spring" },
  { name: "Jerusalem Artichokes (Sunchokes)", category: "Root Vegetables & Alliums", season: "Spring" },
  { name: "Horseradish", category: "Root Vegetables & Alliums", season: "Spring" },
  { name: "Leaf Lettuce", category: "Leafy & Cooking Greens", season: "Early Spring" },
  { name: "Romaine Lettuce", category: "Leafy & Cooking Greens", season: "Early Spring" },
  { name: "Butterhead Lettuce", category: "Leafy & Cooking Greens", season: "Early Spring" },
  { name: "Spinach", category: "Leafy & Cooking Greens", season: "Early Spring" },
  { name: "Swiss Chard", category: "Leafy & Cooking Greens", season: "Early Spring" },
  { name: "Kale", category: "Leafy & Cooking Greens", season: "Early Spring" },
  { name: "Collard Greens", category: "Leafy & Cooking Greens", season: "Early Spring" },
  { name: "Mustard Greens", category: "Leafy & Cooking Greens", season: "Early Spring" },
  { name: "Turnip Greens", category: "Leafy & Cooking Greens", season: "Early Spring" },
  { name: "Arugula", category: "Leafy & Cooking Greens", season: "Early Spring" },
  { name: "Bok Choy", category: "Leafy & Cooking Greens", season: "Early Spring" },
  { name: "Napa Cabbage", category: "Leafy & Cooking Greens", season: "Early Spring" },
  { name: "Green Cabbage", category: "Leafy & Cooking Greens", season: "Early Spring" },
  { name: "Red Cabbage", category: "Leafy & Cooking Greens", season: "Early Spring" },
  { name: "Broccoli", category: "Leafy & Cooking Greens", season: "Early Spring" },
  { name: "Cauliflower", category: "Leafy & Cooking Greens", season: "Early Spring" },
  { name: "Brussels Sprouts", category: "Leafy & Cooking Greens", season: "Summer" },
  { name: "Kohlrabi", category: "Leafy & Cooking Greens", season: "Early Spring" },
  { name: "Radicchio", category: "Leafy & Cooking Greens", season: "Fall" },
  { name: "Endive", category: "Leafy & Cooking Greens", season: "Fall" },
  { name: "Escarole", category: "Leafy & Cooking Greens", season: "Fall" },
  { name: "Mizuna", category: "Leafy & Cooking Greens", season: "Early Spring" },
  { name: "Tatsoi", category: "Leafy & Cooking Greens", season: "Fall" },
  { name: "Watercress", category: "Leafy & Cooking Greens", season: "Spring" },
  { name: "Sorrel", category: "Leafy & Cooking Greens", season: "Spring" },
  { name: "Celery", category: "Leafy & Cooking Greens", season: "Late Winter" },
  { name: "Bulb Fennel", category: "Leafy & Cooking Greens", season: "Spring" },
  { name: "English Peas", category: "Vegetables", season: "Early Spring" },
  { name: "Snap Peas", category: "Vegetables", season: "Early Spring" },
  { name: "Snow Peas", category: "Vegetables", season: "Early Spring" },
  { name: "Fava Beans", category: "Vegetables", season: "Early Spring" },
  { name: "Asparagus", category: "Root Vegetables & Alliums", season: "Dormant Season" },
  { name: "Rhubarb", category: "Root Vegetables & Alliums", season: "Dormant Season" },
  { name: "Sweet Basil", category: "Herbs", season: "Late Spring" },
  { name: "Thai Basil", category: "Herbs", season: "Late Spring" },
  { name: "Cilantro", category: "Herbs", season: "Early Spring" },
  { name: "Flat-Leaf Parsley", category: "Herbs", season: "Early Spring" },
  { name: "Curly Parsley", category: "Herbs", season: "Early Spring" },
  { name: "Dill", category: "Herbs", season: "Spring" },
  { name: "Chives", category: "Herbs", season: "Spring" },
  { name: "Garlic Chives", category: "Herbs", season: "Spring" },
  { name: "Oregano", category: "Herbs", season: "Spring" },
  { name: "Thyme", category: "Herbs", season: "Spring" },
  { name: "Rosemary", category: "Herbs", season: "Spring" },
  { name: "Sage", category: "Herbs", season: "Spring" },
  { name: "Mint", category: "Herbs", season: "Spring" },
  { name: "Lemon Balm", category: "Herbs", season: "Spring" },
  { name: "Tarragon", category: "Herbs", season: "Spring" },
  { name: "Marjoram", category: "Herbs", season: "Spring" },
  { name: "Lavender", category: "Herbs", season: "Spring" },
  { name: "Stevia", category: "Herbs", season: "Late Spring" },
  { name: "Lemongrass", category: "Herbs", season: "Late Spring" },
  { name: "Catnip", category: "Herbs", season: "Spring" },
  { name: "Apples", category: "Fruit Trees", season: "Dormant Season" },
  { name: "Pears", category: "Fruit Trees", season: "Dormant Season" },
  { name: "Peaches", category: "Fruit Trees", season: "Dormant Season" },
  { name: "Plums", category: "Fruit Trees", season: "Dormant Season" },
  { name: "Sweet Cherries", category: "Fruit Trees", season: "Dormant Season" },
  { name: "Tart Cherries", category: "Fruit Trees", season: "Dormant Season" },
  { name: "Figs", category: "Fruit Trees", season: "Dormant Season" },
  { name: "Pawpaws", category: "Fruit Trees", season: "Dormant Season" },
  { name: "American Persimmons", category: "Fruit Trees", season: "Dormant Season" },
  { name: "Mulberries", category: "Fruit Trees", season: "Dormant Season" },
  { name: "Quince", category: "Fruit Trees", season: "Dormant Season" },
  { name: "Pomegranate", category: "Fruit Trees", season: "Dormant Season" },
  { name: "Blueberries", category: "Berries & Vines", season: "Dormant Season" },
  { name: "Blackberries", category: "Berries & Vines", season: "Dormant Season" },
  { name: "Raspberries", category: "Berries & Vines", season: "Dormant Season" },
  { name: "Strawberries", category: "Berries & Vines", season: "Early Spring" },
  { name: "Table Grapes", category: "Berries & Vines", season: "Dormant Season" },
  { name: "Muscadine Grapes", category: "Berries & Vines", season: "Dormant Season" },
  { name: "Elderberries", category: "Berries & Vines", season: "Dormant Season" },
  { name: "Currants", category: "Berries & Vines", season: "Dormant Season" },
  { name: "Gooseberries", category: "Berries & Vines", season: "Dormant Season" },
  { name: "Pecans", category: "Nuts", season: "Dormant Season" },
  { name: "Black Walnuts", category: "Nuts", season: "Dormant Season" },
  { name: "Hazelnuts", category: "Nuts", season: "Dormant Season" },
  { name: "Chestnuts", category: "Nuts", season: "Dormant Season" },
  { name: "Marigolds", category: "Flowers & Pollinator Plants", season: "Late Spring" },
  { name: "Zinnias", category: "Flowers & Pollinator Plants", season: "Late Spring" },
  { name: "Sunflowers", category: "Flowers & Pollinator Plants", season: "Late Spring" },
  { name: "Nasturtiums", category: "Flowers & Pollinator Plants", season: "Late Spring" },
  { name: "Calendula", category: "Flowers & Pollinator Plants", season: "Early Spring" },
  { name: "Cosmos", category: "Flowers & Pollinator Plants", season: "Late Spring" },
  { name: "Borage", category: "Flowers & Pollinator Plants", season: "Spring" },
  { name: "Dahlias", category: "Flowers & Pollinator Plants", season: "Spring" },
];

export const SEASONS = ["All", "Late Winter", "Early Spring", "Spring", "Late Spring", "Summer", "Fall", "Dormant Season"];